QuanLyBanSach/QuanLySach/QuanLySach/Models/TinTuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int Ma { get; set; }
        public string TieuDe { get; set; }
        public string MoTaNgan { get; set; }
        public string MoTa { get; set; }
        public string Anh { get; set; }
        public int MaCM { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string TacGia { get; set; }
    
        public virtual ChuyenMuc ChuyenMuc { get; set; }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySach.Models;

namespace QuanLySach.Areas.Admin.Controllers
{
    public class TinTucsController : Controller
    {
        private QuanLySachEntities db = new QuanLySachEntities();

        // GET: Admin/TinTucs
        public ActionResult Index()
        {
            var tinTucs = db.TinTucs.Include(t => t.ChuyenMuc);
            return View(tinTucs.ToList());
        }

        // GET: Admin/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten");
            return View();
        }

        // POST: Admin/TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Ma,TieuDe,MoTaNgan,MoTa,Anh,MaCM,NgayDang,TacGia")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten", tinTuc.MaCM);
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten", tinTuc.MaCM);
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Ma,TieuDe,MoTaNgan,MoTa,Anh,MaCM,NgayDang,TacGia")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten", tinTuc.MaCM);
            return View(tinTuc);
        }
        // GET: Admin/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Delete/5
        
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/TinTucs/Create.cshtml
@model QuanLySach.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        <div class="page-header">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="title">
                        <h4>Thêm tin tức</h4>
                    </div>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index","Default")">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Thêm tin tức</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                            January 2018
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Export List</a>
                            <a class="dropdown-item" href="#">Policies</a>
                            <a class="dropdown-item" href="#">View Assets</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Default Basic Forms Start -->
        <div class="pd-20 card-box mb-30">
            <div class="clearfix">
                <div class="pull-left">
                    <h4 class="text-blue h4">Thêm tin tức</h4>
                    <p class="mb-30">All bootstrap element classies</p>
                </div>
                <div class="pull-right">
                    <a href="#basic-form1" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="collapse" role="button"></a>
                </div>
            </div>
            <form method="post">
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Tiêu đề</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="TieuDe" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Mô tả ngắn</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" placeholder="" type="search" name="MoTaNgan" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label"> Mô tả</label>
                    <div class="col-sm-12 col-md-10">
                        <textarea class="form-control" name="MoTa" id="MoTa"></textarea>
                        <script type="text/javascript">
                            CKEDITOR.replace("MoTa");
                        </script>
                        <script>
                            $("#browse").click(function () {
                                var finder = new CKFinder();
                                finder.selectActionFunction = function (fileUrl) {
                                    $("#MoTa").val(fileUrl);
                                }
                                finder.popup();
                            });
                        </script>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Ảnh</label>
                    <div class="col-sm-12 col-md-10 d-flex">
                        <input class="form-control" placeholder="" type="text" name="Anh" required id="Anh">
                        <input type="button" class="btn btn-success" id="upload-image" value="upload ảnh" required>
                        <script>
                            $("#upload-image").click(function () {
                                var finder = new CKFinder();
                                finder.selectActionFunction = function (fileUrl) {
                                    $("#Anh").val(fileUrl);
                                }
                                finder.popup();
                            });
                        </script>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Chuyên mục</label>
                    <div class="col-sm-12 col-md-10">
                        @Html.DropDownList("MaCM", null, htmlAttributes: new { @class = "custom-select" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Tác gia</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" placeholder="" type="search" name="TacGia" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Tác gia</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" placeholder="" type="date" name="NgayDang" required>
                    </div>
                </div>
                <div class="btn-list">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Thêm</button>
                    <a href="@Url.Action("Index","TinTucs")" class="btn btn-secondary btn-lg btn-block">Quay lại</a>
                </div>
            </form>
        </div>
    </div>
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/TinTucs/Delete.cshtml
@model QuanLySach.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TinTuc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaNgan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaNgan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuyenMuc.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuyenMuc.Ten)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/TinTucs/Details.cshtml
@model QuanLySach.Models.TinTuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        <div class="card-box mb-30">
            <div class="pd-20">
                <dl class="dl-horizontal">
                    <dt>
                        Tiêu đề
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TieuDe)
                    </dd>

                    <dt>
                        Mô tả ngắn
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MoTaNgan)
                    </dd>

                    <dt>
                        Mô tả
                    </dt>

                    <dd>
                        @Html.Raw(Model.MoTa)
                    </dd>

                    <dt>
                        Hình ảnh
                    </dt>

                    <dd>
                        <img src="@Model.Anh" width="300px" height="300px" />
                    </dd>
                    <dt>
                        Tên chuyên mục
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ChuyenMuc.Ten)
                    </dd>

                    <dt>
                        Tên tác gia
                    </dt>
                    <dd>
                        @Model.TacGia
                    </dd>
                    <dt>
                        Ngày đăng
                    </dt>
                    <dd>
                        @Model.NgayDang
                    </dd>

                </dl>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Ma }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>
        </div>
     </div>
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/TinTucs/Edit.cshtml
@model QuanLySach.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        <div class="page-header">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="title">
                        <h4>Sửa tin tức</h4>
                    </div>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index","Default")">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Sửa tin tức</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                            January 2018
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Export List</a>
                            <a class="dropdown-item" href="#">Policies</a>
                            <a class="dropdown-item" href="#">View Assets</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Default Basic Forms Start -->
        <div class="pd-20 card-box mb-30">
            <div class="clearfix">
                <div class="pull-left">
                    <h4 class="text-blue h4">Sửa tin tức</h4>
                </div>
                <div class="pull-right">
                    <a href="#basic-form1" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="collapse" role="button"></a>
                </div>
            </div>
            <form method="post">
                @Html.HiddenFor(model => model.Ma)
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Tiêu đề</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" value="@Model.TieuDe" name="TieuDe" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Mô tả ngắn</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" placeholder="" type="search" name="MoTaNgan" value="@Model.MoTaNgan" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label"> Mô tả</label>
                    <div class="col-sm-12 col-md-10">
                        <textarea class="form-control" name="MoTa" id="MoTa">
                              @Model.MoTa
                        </textarea>
                        <script type="text/javascript">
                            CKEDITOR.replace("MoTa");
                        </script>
                        <script>
                            $("#browse").click(function () {
                                var finder = new CKFinder();
                                finder.selectActionFunction = function (fileUrl) {
                                    $("#MoTa").val(fileUrl);
                                }
                                finder.popup();
                            });
                        </script>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Ảnh</label>
                    <div class="col-sm-12 col-md-10 d-flex">
                        <input class="form-control" placeholder="" type="text" name="Anh" value="@Model.Anh" required id="Anh">
                        <input type="button" class="btn btn-success" id="upload-image" value="upload ảnh" required>
                        <script>
                            $("#upload-image").click(function () {
                                var finder = new CKFinder();
                                finder.selectActionFunction = function (fileUrl) {
                                    $("#Anh").val(fileUrl);
                                }
                                finder.popup();
                            });
                        </script>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Chuyên mục</label>
                    <div class="col-sm-12 col-md-10">
                        @Html.DropDownList("MaCM", null, htmlAttributes: new { @class = "custom-select", @value = Model.MaCM })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Tác gia</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" placeholder="" type="search" name="TacGia" value="@Model.TacGia" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Tác gia</label>
                    <div class="col-sm-12 col-md-10">
                        @{ DateTime time = DateTime.Parse(Model.NgayDang.ToString()); }
                        <input class="form-control" placeholder="" value="@time.ToString("yyyy-MM-dd")" type="date" name="NgayDang" required>
                    </div>
                </div>
                <div class="btn-list">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Sửa</button>
                    <a href="@Url.Action("Index","TinTucs")" class="btn btn-secondary btn-lg btn-block">Quay lại</a>
                </div>
            </form>
        </div>
    </div>
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/TinTucs/Index.cshtml
@model IEnumerable<QuanLySach.Models.TinTuc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        <div class="page-header">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="title">
                        <h4>Danh sách tin tức</h4>
                    </div>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index","Default")">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Danh sách tin tức</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <div class="dropdown">
                        <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                            January 2018
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Export List</a>
                            <a class="dropdown-item" href="#">Policies</a>
                            <a class="dropdown-item" href="#">View Assets</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Simple Datatable start -->
        <div class="card-box mb-30">
            <div class="pd-20">
                <h4 class="text-blue h4">Danh sách tin tức</h4>
                <p class="mb-0">Thêm sản phẩm<a class="text-primary" href="@Url.Action("Create","TinTucs")">Click Here</a></p>
            </div>
            <div class="pb-20">
                <table class="data-table table stripe hover nowrap">
                    <thead>
                        <tr>
                            <th class="table-plus datatable-nosort">Tiêu đề</th>
                            <th>Mô tả ngắn</th>
                            <th>Hình ảnh</th>
                            <th>Mã chuyên mục</th>
                            <th>Ngày đăng</th>
                            <th>Tác gia</th>
                            <th class="datatable-nosort">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td class="table-plus">@item.TieuDe</td>
                            <td>@item.MoTaNgan</td>
                            <td><img src="@item.Anh" height="50px" width="50px" /></td>
                            <td>@item.ChuyenMuc.Ten</td>
                            <td>@item.NgayDang</td>
                            <td>@item.TacGia</td>
                            <td>
                                <div class="dropdown">
                                    <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                                        <i class="dw dw-more"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                        <a class="dropdown-item" href="@Url.Action("Details","TinTucs", new { id = item.Ma })"><i class="dw dw-eye"></i> View</a>
                                        <a class="dropdown-item" href="@Url.Action("Edit","TinTucs", new { id = item.Ma })"><i class="dw dw-edit2"></i> Edit</a>
                                        <a class="dropdown-item" href="@Url.Action("DeleteConfirmed","TinTucs", new { id = item.Ma })"><i class="dw dw-delete-3"></i> Delete</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>