QuanLyBanSach/QuanLySach/QuanLySach/Controllers/LoaiSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLySach.Models;
using PagedList;

namespace QuanLySach.Controllers
{
    public class LoaiSPController : Controller
    {
        // GET: LoaiSP
        QuanLySachEntities db = new QuanLySachEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult XemLoaiSP(int? ma, int? page)
        {
            if (page == null)
            {
                page = 1;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            var LoaiSP = db.SanPhams.Where(x => x.MaLoai == ma).OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
            if (LoaiSP.Count() >  0)
            {

                LoaiSP = db.SanPhams.Where(x => x.MaLoai == ma).OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
                ViewBag.Ma = ma;
                ViewBag.TheLoai = db.SanPhams.Where(x => x.MaLoai == ma).FirstOrDefault().LoaiSP.Ten;
                ViewBag.count = db.SanPhams.Where(x => x.MaLoai == ma).ToList().Count();
            }
            else
            {
                LoaiSP = db.SanPhams.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
            }
            ViewBag.LoaiSP = db.LoaiSPs.ToList();
            return View(LoaiSP);
        }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLySach.Models;
using PagedList;
namespace QuanLySach.Controllers
{
    public class ShopController : Controller
    {
        QuanLySachEntities db = new QuanLySachEntities();
        // GET: Shop
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Shop( int? page , string tensp , decimal? gia)
        {
            if (page == null)
            {
                page = 1;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            var  LoaiSP = db.SanPhams.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);

            if(tensp != null)
            {
                LoaiSP = db.SanPhams.Where(x=>x.Ten.Contains(tensp)).OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
            }


            if (gia > 0)
            {
                LoaiSP = db.SanPhams.Where(x => x.Gia <= gia).OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
            }

            ViewBag.LoaiSP = db.LoaiSPs.ToList();
            return View(LoaiSP);
        }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Views/Shop/Shop.cshtml
@model PagedList.IPagedList<QuanLySach.Models.SanPham>
@using PagedList.Mvc;
@using QuanLySach.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ht__bradcaump__area bg-image--6" style="background-image:url(../Assets/images/banner/banner4.jpg)">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Cửa hàng</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="@Url.Action("Index","Home")">Trang chủ</a>
                        <span class="brd-separetor">/</span>
                        <span class="breadcrumb_item active">Cửa hàng</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- Start Shop Page -->
<div class="page-shop-sidebar left--sidebar bg--white section-padding--lg">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-12 order-2 order-lg-1 md-mt-40 sm-mt-40">
                <div class="shop__sidebar">
                    <aside class="wedget__categories poroduct--cat">
                        <h3 class="wedget__title">Thể loại</h3>
                        <ul>
                            @foreach (var item in ViewBag.LoaiSP)
                            {

                                <li><a href="@Url.Action("XemLoaiSP","LoaiSP" , new { ma = item.Ma})">@item.Ten <span>(@item.SanPhams.Count)</span></a></li>
                            }

                        </ul>
                    </aside>
                    <aside class="wedget__categories pro--range">
                        <h3 class="wedget__title">Lọc theo giá</h3>
                        <div class="content-shopby">
                            <div class="price_filter s-filter clear">
                                <form action="@Url.Action("Shop","Shop")" method="GET" id="range_item">
                                    <input type="range"  id="slider-range" min="10000" width="400px" max="500000" name="gia" oninput="document.getElementById('input_range').value = this.value"  />
                                    <div class="slider__range--output">
                                        <div class="price__output--wrap">
                                            <div class="price--output">
                                                <span>Giá :</span> <input type="text" id="input_range" value="250000" disabled />VND
                                            </div>
                                            <div class="price--filter">
                                                <a style="color:white" onclick="document.getElementById('range_item').submit()">Lọc</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </aside>
                    <aside class="wedget__categories poroduct--tag">
                        <h3 class="wedget__title">Nhãn sản phẩm</h3>
                        <ul>
                            @foreach (var item in ViewBag.LoaiSP)
                            {

                                <li><a href="@Url.Action("XemLoaiSP","LoaiSP" , new { ma = item.Ma})">@item.Ten <span>(@item.SanPhams.Count)</span></a></li>
                            }
                        </ul>
                    </aside>
                </div>
            </div>
            <div class="col-lg-9 col-12 order-1 order-lg-2">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="shop__list__wrapper d-flex flex-wrap flex-md-nowrap justify-content-between">
                            <div class="shop__list nav justify-content-center" role="tablist">
                                <a class="nav-item nav-link active" data-toggle="tab" href="#nav-grid" role="tab"><i class="fa fa-th"></i></a>
                                <a class="nav-item nav-link" data-toggle="tab" href="#nav-list" role="tab"><i class="fa fa-list"></i></a>
                            </div>
                            <p>Showing 1–12 of 40 results</p>
                            <div class="orderby__wrapper">
                                <form id="timkiemloai" method="get" action="@Url.Action("XemLoaiSP","LoaiSP")">
                                    <span>Sort By</span>
                                    <select class="shot__byselect" name="ma" onchange="document.getElementById('timkiemloai').submit()">
                                        <option value="">--Chon--</option>
                                        @foreach (var item in ViewBag.LoaiSP)
                                        {

                                            <option value="@item.Ma">@item.Ten</option>
                                        }
                                    </select>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab__container">
                    <div class="shop-grid tab-pane fade show active" id="nav-grid" role="tabpanel">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                <!-- Start Single Product -->
                                <div class="product product__style--3 col-lg-4 col-md-4 col-sm-6 col-12">
                                    <div class="product__thumb">
                                        <a class="first__img" href="@Url.Action("SingleProduct","SinglePage" , new { ma = item.Ma })"><img src="@item.Anh" alt="product image"></a>
                                        <a class="second__img animation1" href="@Url.Action("SingleProduct","SinglePage" , new { ma = item.Ma })"><img src="@item.Anh" alt="product image"></a>
                                        <div class="hot__box">
                                            <span class="hot-label">@item.GiamGia</span>
                                        </div>
                                    </div>
                                    <div class="product__content content--center">
                                        <h4><a href="@Url.Action("SingleProduct","SinglePage" , new { ma = item.Ma })">@item.Ten</a></h4>
                                        <ul class="prize d-flex">
                                            @{ decimal gia = (decimal)item.Gia;}
                                            <li>@gia.ToString("##,#") VND</li>
                                        </ul>
                                        <div class="action">
                                            <div class="actions_inner">
                                                <ul class="add_to_links">
                                                    <li><a class="cart" href="@Url.Action("XemGioHang","GioHangs")"><i class="bi bi-shopping-bag4"></i></a></li>
                                                    <li><a class="wishlist" href="@Url.Action("ThemGioHang","GioHangs" , new { masp = item.Ma , sl = 1})"><i class="bi bi-shopping-cart-full"></i></a></li>
                                                    <li><a class="compare" href="@Url.Action("ThemWishList","wishlist" , new { masp = item.Ma})"><i class="bi bi-heart-beat"></i></a></li>
                                                    <li><a title="Quick View" class="quickview modal-view detail-link" href="@Url.Action("SingleProduct","SinglePage" , new { ma = item.Ma })"><i class="bi bi-search"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="product__hover--content">
                                            <ul class="rating d-flex">
                                                <li class="on"><i class="fa fa-star-o"></i></li>
                                                <li class="on"><i class="fa fa-star-o"></i></li>
                                                <li class="on"><i class="fa fa-star-o"></i></li>
                                                <li><i class="fa fa-star-o"></i></li>
                                                <li><i class="fa fa-star-o"></i></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Product -->
                            }
                        </div>
                            @Html.PagedListPager(Model, page => Url.Action("Shop", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "Get", UpdateTargetId = "sp_area" }))
                    </div>
                    <div class="shop-grid tab-pane fade" id="nav-list" role="tabpanel">
                        <div class="list__view__wrapper">
                            <!-- Start Single Product -->
                            @foreach (var item in Model)
                            {
                                <div class="list__view mt--40">
                                    <div class="thumb">
                                        <a class="first__img" href="@Url.Action("SingleProduct","SinglePage" , new { ma = item.Ma })"><img src="@item.Anh" alt="product images"></a>
                                        <a class="second__img animation1" href="@Url.Action("SingleProduct","SinglePage" , new { ma = item.Ma })"><img src="@item.Anh" alt="product images"></a>
                                    </div>
                                    <div class="content">
                                        <h2><a href="@Url.Action("SingleProduct","SinglePage" , new { ma = item.Ma })">@item.Ten</a></h2>
                                        <ul class="rating d-flex">
                                            <li class="on"><i class="fa fa-star-o"></i></li>
                                            <li class="on"><i class="fa fa-star-o"></i></li>
                                            <li class="on"><i class="fa fa-star-o"></i></li>
                                            <li class="on"><i class="fa fa-star-o"></i></li>
                                            <li><i class="fa fa-star-o"></i></li>
                                            <li><i class="fa fa-star-o"></i></li>
                                        </ul>
                                        @{ decimal gia = (decimal)item.Gia;}
                                        <ul class="prize__box">
                                            <li>@gia.ToString("##,#") VND</li>
                                        </ul>
                                        <p>@item.Mota</p>
                                        <ul class="cart__action d-flex">
                                            <li class="cart"><a href="@Url.Action("ThemGioHang","GioHangs" , new { masp = item.Ma , sl = 1})">Add to cart</a></li>
                                            <li class="wishlist"><a href="@Url.Action("ThemWishList","wishlist" , new { masp = item.Ma})"></a></li>
                                        </ul>

                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>