QuanLyBanSach/QuanLySach/QuanLySach/Models/LoaiSP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Controllers/LoaiSPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySach.Models;

namespace QuanLySach.Areas.Admin.Controllers
{
    public class LoaiSPsController : Controller
    {
        private QuanLySachEntities db = new QuanLySachEntities();

        // GET: Admin/LoaiSPs
        public ActionResult Index()
        {
            return View(db.LoaiSPs.ToList());
        }

        // GET: Admin/LoaiSPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // GET: Admin/LoaiSPs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ma,Ten,MoTa")] LoaiSP loaiSP)
        {
            if (ModelState.IsValid)
            {
                db.LoaiSPs.Add(loaiSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loaiSP);
        }

        // GET: Admin/LoaiSPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // POST: Admin/LoaiSPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma,Ten,MoTa")] LoaiSP loaiSP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiSP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaiSP);
        }

        // GET: Admin/LoaiSPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }
        // POST: Admin/LoaiSPs/Delete/5
        public ActionResult DeleteConfirmed(int id)
        {
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            db.LoaiSPs.Remove(loaiSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Controllers/LoaiSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLySach.Models;
using PagedList;

namespace QuanLySach.Controllers
{
    public class LoaiSPController : Controller
    {
        // GET: LoaiSP
        QuanLySachEntities db = new QuanLySachEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult XemLoaiSP(int? ma, int? page)
        {
            if (page == null)
            {
                page = 1;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            var LoaiSP = db.SanPhams.Where(x => x.MaLoai == ma).OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
            if (LoaiSP.Count() >  0)
            {

                LoaiSP = db.SanPhams.Where(x => x.MaLoai == ma).OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
                ViewBag.Ma = ma;
                ViewBag.TheLoai = db.SanPhams.Where(x => x.MaLoai == ma).FirstOrDefault().LoaiSP.Ten;
                ViewBag.count = db.SanPhams.Where(x => x.MaLoai == ma).ToList().Count();
            }
            else
            {
                LoaiSP = db.SanPhams.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize);
            }
            ViewBag.LoaiSP = db.LoaiSPs.ToList();
            return View(LoaiSP);
        }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/LoaiSPs/Create.cshtml
@model QuanLySach.Models.LoaiSP

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        <div class="page-header">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="title">
                        <h4>Thêm loại sản phẩm</h4>
                    </div>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index","Default")">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Thêm loại sản phẩm</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                            January 2018
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Export List</a>
                            <a class="dropdown-item" href="#">Policies</a>
                            <a class="dropdown-item" href="#">View Assets</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Default Basic Forms Start -->
        <div class="pd-20 card-box mb-30">
            <div class="clearfix">
                <div class="pull-left">
                    <h4 class="text-blue h4">Thêm loại sản phẩm</h4>
                </div>
                <div class="pull-right">
                    <a href="#basic-form1" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="collapse" role="button"></a>
                </div>
            </div>
            <form  method="post">
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Thể loại sách</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="Ten" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Mô tả</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" placeholder="" type="search" name="MoTa" required>
                    </div>
                </div>
                <div class="btn-list">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Thêm</button>
                    <a href="@Url.Action("Index","LoaiSPs")" class="btn btn-secondary btn-lg btn-block">Quay lại</a>
                </div>
            </form>
        </div>
</div>
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/LoaiSPs/Delete.cshtml
@model QuanLySach.Models.LoaiSP

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LoaiSP</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/LoaiSPs/Details.cshtml
@model QuanLySach.Models.LoaiSP

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        <div class="card-box mb-30">
            <div class="pd-20">
                <dl class="dl-horizontal">
                    <dt>
                        Tên thể loại
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Ten)
                    </dd>

                    <dt>
                        Mô tả
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MoTa)
                    </dd>
                </dl>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Ma }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>
        </div>
    </div>
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/LoaiSPs/Edit.cshtml
@model QuanLySach.Models.LoaiSP

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        <div class="page-header">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="title">
                        <h4>Sửa loại sản phẩm</h4>
                    </div>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index","Default")">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Sửa loại sản phẩm</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                            January 2018
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Export List</a>
                            <a class="dropdown-item" href="#">Policies</a>
                            <a class="dropdown-item" href="#">View Assets</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Default Basic Forms Start -->
        <div class="pd-20 card-box mb-30">
            <div class="clearfix">
                <div class="pull-left">
                    <h4 class="text-blue h4">Sửa loại sản phẩm</h4>
                </div>
                <div class="pull-right">
                    <a href="#basic-form1" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="collapse" role="button"></a>
                </div>
            </div>
            <form method="post">
                @Html.HiddenFor(model => model.Ma)
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Thể loại sách</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="Ten" value="@Model.Ten"  required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Mô tả</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" placeholder="" type="search" name="MoTa" value="@Model.MoTa" required>
                    </div>
                </div>
                <div class="btn-list">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Sửa</button>
                    <a href="@Url.Action("Index","LoaiSPs")" class="btn btn-secondary btn-lg btn-block">Quay lại</a>
                </div>
            </form>
        </div>
    </div>
</div>

QuanLyBanSach/QuanLySach/QuanLySach/Areas/Admin/Views/LoaiSPs/Index.cshtml
@model IEnumerable<QuanLySach.Models.LoaiSP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Danh sách sản phẩm</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="@Url.Action("Index","Default")">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Danh sách sản phẩm</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right">
                        <div class="dropdown">
                            <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                                January 2018
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">Export List</a>
                                <a class="dropdown-item" href="#">Policies</a>
                                <a class="dropdown-item" href="#">View Assets</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Simple Datatable start -->
            <div class="card-box mb-30">
                <div class="pd-20">
                    <h4 class="text-blue h4">Danh sách loại sản phẩm</h4>
                    <p class="mb-0">Thêm loại sản phẩm<a class="text-primary" href="@Url.Action("Create","LoaiSPs")">Click Here</a></p>
                </div>
                <div class="pb-20">
                    <table class="data-table table stripe hover nowrap">
                        <thead>
                            <tr>
                                <th class="table-plus datatable-nosort">Tên</th>
                                <th>Mô tả</th>
                                <th>Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="table-plus">@item.Ten</td>
                                    <td>@item.MoTa</td>
                                    <td>
                                        <div class="dropdown">
                                            <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                                                <i class="dw dw-more"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                                <a class="dropdown-item" href="@Url.Action("Details","LoaiSPs", new { id = item.Ma })"><i class="dw dw-eye"></i> View</a>
                                                <a class="dropdown-item" href="@Url.Action("Edit","LoaiSPs", new { id = item.Ma })"><i class="dw dw-edit2"></i> Edit</a>
                                                <a class="dropdown-item" href="@Url.Action("DeleteConfirmed","LoaiSPs", new { id = item.Ma })"><i class="dw dw-delete-3"></i> Delete</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>