QuanLyBanSach/QuanLySach/QuanLySach/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuanLySach.Models
{
    public class GioHang
    {
        public SanPham sp { get; set; }
        public int Soluong { get; set; }
        public GioHang()
        {

        }
        public GioHang(SanPham spm, int sl)
        {
            this.sp = spm;
            this.Soluong = sl;
        }
    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Controllers/GioHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLySach.Models;

namespace QuanLySach.Controllers
{
    public class GioHangsController : Controller
    {
        // GET: GioHangs
        QuanLySachEntities db = new QuanLySachEntities();
        string giohang = "GioHang";
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ThemGioHang(int masp, int sl)
        {

            var gh = (List<GioHang>)Session[giohang];
            var sp = db.SanPhams.Find(masp);

            // kiem tra 

            if (gh == null)
            {
                var gio_hang_mois = new List<GioHang>();

                GioHang gh_moi = new GioHang();
                gh_moi.sp = sp;
                gh_moi.Soluong = sl;
                gio_hang_mois.Add(gh_moi);
                Session[giohang] = gio_hang_mois;
            }
            else
            {
                if (gh.Exists(x => x.sp.Ma == masp))
                {
                    var sanpham = gh.Where(s => s.sp.Ma == masp).FirstOrDefault();
                    sanpham.Soluong = sanpham.Soluong + sl;


                }
                else
                {
                    GioHang gh_moi = new GioHang();
                    gh_moi.sp = sp;
                    gh_moi.Soluong = sl;
                    gh.Add(gh_moi);

                }
                Session[giohang] = gh;
            }

            return Redirect(Request.UrlReferrer.ToString());

        }
        public ActionResult XemGioHang()
        {
            if (Session[giohang] == null)
            {
                return Redirect(Request.UrlReferrer.ToString());
            }
            else
            {
                List<GioHang> gh = (List<GioHang>)Session[giohang];
                return View(gh);
            }
        }
        public ActionResult XoaSP(int masp)
        {

            var gh = (List<GioHang>)Session[giohang];
            var sp = db.SanPhams.Find(masp);
            if (gh.Exists(x => x.sp.Ma == masp))
            {
                var sanpham = gh.Where(s => s.sp.Ma == masp).FirstOrDefault();
                gh.Remove(sanpham);
                Session[giohang] = gh;
            }
            return Redirect(Request.UrlReferrer.ToString());

        }
        public ActionResult TangSl(int masp)
        {
            var gh = (List<GioHang>)Session[giohang];
            var sp = db.SanPhams.Find(masp);
            if (gh.Exists(x => x.sp.Ma == masp))
            {
                var sanpham = gh.Where(s => s.sp.Ma == masp).FirstOrDefault();
                sanpham.Soluong = sanpham.Soluong + 1;
                Session[giohang] = gh;

            }
            return Redirect(Request.UrlReferrer.ToString());

        }
        public ActionResult GiamSl(int masp)
        {
            var gh = (List<GioHang>)Session[giohang];
            var sp = db.SanPhams.Find(masp);
            if (gh.Exists(x => x.sp.Ma == masp))
            {
                var sanpham = gh.Where(s => s.sp.Ma == masp).FirstOrDefault();
                if (sanpham.Soluong > 0)
                {
                    sanpham.Soluong = sanpham.Soluong - 1;
                    Session[giohang] = gh;
                }

            }
            return Redirect(Request.UrlReferrer.ToString());

        }
        public ActionResult CheckOut()
        {
            List<GioHang> gh = (List<GioHang>)Session[giohang];
            if (gh == null)
            {
                return Redirect(Request.UrlReferrer.ToString());
            }
            else
            {
                return View(gh);
            }
        }
        public ActionResult CheckOutProduct(int makh, string tenkh, string diachi, string SoDienThoai, string email, string diachigiaohang, string checkGiaoHang)
        {
            List<GioHang> gh = (List<GioHang>)Session[giohang];


            KhachHang kh = db.KhachHangs.Find(makh);

            kh.Ten = tenkh;
            kh.DiaChi = diachi;
            kh.DienThoai = SoDienThoai;
            kh.Email = email;
            db.Entry(kh).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            DonHang dh = new DonHang();
            dh.MaKhachHang = makh;
            dh.NgayDatHang = DateTime.Now;
            dh.PhiGiao = 0;
            dh.TenNguoiNhan = tenkh;
            if (checkGiaoHang == "0")
            {
                dh.DiaChi = diachigiaohang;
            }
            else
            {
                dh.DiaChi = diachi;
            }
            dh.DienThoai = SoDienThoai;
            dh.Email = email;
            dh.TrangThai = false;
            db.DonHangs.Add(dh);
            db.SaveChanges();
            int mdh = db.DonHangs.OrderByDescending(x => x.Ma).FirstOrDefault().Ma;


            foreach (var item in gh)
            {
                ChiTietDonHang ctd = new ChiTietDonHang();
                ctd.MaDH = mdh;
                ctd.MaSP = item.sp.Ma;
                ctd.SoLuong = item.Soluong;
                ctd.DonGia = item.sp.Gia;
                db.ChiTietDonHangs.Add(ctd);
                db.SaveChanges();
            }
            DonHang ttdh = db.DonHangs.Find(mdh);
            Session["TTDonHang"] = ttdh;
            return RedirectToAction("DatHangTC");

        }


        public ActionResult LoginAcc()
        {
            List<GioHang> gh = (List<GioHang>)Session[giohang];
            KhachHang kh = (KhachHang)Session["KhachHang"];
            if (gh == null)
            {
                return Redirect(Request.UrlReferrer.ToString());
            }
            else
            {
                if(kh != null)
                {
                    return Redirect("CheckOut");
                }
                else
                {
                   return View(gh);
                }
            }
        }
        [HttpPost]
        public ActionResult LoginAcc(string SoDienThoai, string MatKhau)
        {
            List<GioHang> gh = (List<GioHang>)Session[giohang];
            var isKH = db.KhachHangs.Where(x => x.DienThoai == SoDienThoai && x.Password == MatKhau).FirstOrDefault();
            if (isKH != null)
            {
                Session["KhachHang"] = isKH;
                return Redirect("CheckOut");
            }
            else
            {
                ViewBag.mess = "Đăng nhập không thành công";
            }
            return View(gh);
        }
        public ActionResult CreateAcc()
        {
            List<GioHang> gh = (List<GioHang>)Session[giohang];
            if (gh == null)
            {
                return Redirect(Request.UrlReferrer.ToString());
            }
            else
            {
                return View(gh);
            }
        }

        [HttpPost]
        public ActionResult CreateAcc(string tenkh, string diachi, string sodienthoai, string password, string email, string diachigiaohang, string checkGiaoHang)
        {
            List<GioHang> gh = (List<GioHang>)Session[giohang];

            KhachHang kh = new KhachHang();

            kh.Ten = tenkh;
            kh.DiaChi = diachi;
            kh.DienThoai = sodienthoai;
            kh.Email = email;
            kh.Password = password;
            db.KhachHangs.Add(kh);
            db.SaveChanges();

            var makh = db.KhachHangs.OrderByDescending(x => x.Ma).FirstOrDefault().Ma;

            DonHang dh = new DonHang();
            dh.MaKhachHang = makh;
            dh.NgayDatHang = DateTime.Now;
            dh.PhiGiao = 0;
            dh.TenNguoiNhan = tenkh;
            dh.DienThoai = sodienthoai;
            dh.DiaChi = diachi;
            dh.Email = email;
            if (checkGiaoHang == "0")
            {
                dh.DiaChi = diachigiaohang;
            }
            else
            {
                dh.DiaChi = diachi;
            }
            dh.TrangThai = false;
            db.DonHangs.Add(dh);
            db.SaveChanges();
            int mdh = db.DonHangs.OrderByDescending(x => x.Ma).FirstOrDefault().Ma;
            foreach (var item in gh)
            {
                ChiTietDonHang ctd = new ChiTietDonHang();
                ctd.MaDH = mdh;
                ctd.MaSP = item.sp.Ma;
                ctd.SoLuong = item.Soluong;
                ctd.DonGia = item.sp.Gia;
                db.ChiTietDonHangs.Add(ctd);
                db.SaveChanges();
            }

            DonHang ttdh = db.DonHangs.Find(mdh);
            Session["TTDonHang"] = ttdh;
            return RedirectToAction("DatHangTC");

        }
        public ActionResult DatHangTC()
        {

            var dh = (DonHang)Session["TTDonHang"];
            var ctdh = db.ChiTietDonHangs.Where(x => x.MaDH == dh.Ma).ToList();
            Session[giohang] = null;
            return View(ctdh);

        }

    }
}

QuanLyBanSach/QuanLySach/QuanLySach/Views/GioHangs/CheckOut.cshtml
@model IEnumerable<QuanLySach.Models.GioHang>
@using QuanLySach.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Start Bradcaump area -->
<div class="ht__bradcaump__area bg-image--4" style="background-image:url(../Assets/images/banner/banner4.jpg)">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Tạo tài khoản</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="@Url.Action("Index","Home")">Trang chủ</a>
                        <span class="brd-separetor">/</span>
                        <span class="breadcrumb_item active">Tạo tài khoản</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- Start Checkout Area -->
<section class="wn__checkout__area section-padding--lg bg__white">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-12">
                <form action="@Url.Action("CheckOutProduct","GioHangs")" method="post">
                    <div class="customer_details">
                        <h3>Thông tin khách hàng</h3>
                        @{ KhachHang kh = (KhachHang)Session["KhachHang"]; }
                        <div class="customar__field">
                            <div class="input_box">
                                <label> Tên khách hàng <span>*</span></label>
                                <input type="hidden" value="@kh.Ma" name="makh" required />
                                <input type="text" value="@kh.Ten" name="tenkh" required>
                            </div>
                            <div class="input_box">
                                <label>Địa chỉ <span>*</span></label>
                                <input type="text" placeholder="Street address" value="@kh.DiaChi" id="diachi" name="diachi" required>
                            </div>
                            <div class="margin_between">
                                <div class="input_box space_between">
                                    <label>Số điện thoại <span>*</span></label>
                                    <input type="text" value="@kh.DienThoai" name="SoDienThoai" required>
                                </div>

                                <div class="input_box space_between">
                                    <label>Email  <span>*</span></label>
                                    <input type="email" value="@kh.Email" name="email" required>
                                </div>
                            </div>
                            <div class="input_box">
                                <label>Giao tới địa chỉ khác <span>*</span></label>
                                <input type="text" placeholder="Street address" value="@kh.DiaChi" name="diachigiaohang" required>
                            </div>
                        </div>
                    </div>
                    <div class="create__account d-flex">
                        <input class="input-checkbox btn btn-primary" style="width:100%;" value="Đặt hàng" type="submit">
                    </div>
                </form>
            </div>
            <div class="col-lg-6 col-12 md-mt-40 sm-mt-40">
                <div class="wn__order__box">
                    <h3 class="onder__title">Đơn hàng của bạn</h3>
                    <ul class="order__total">
                        <li>Sản phẩm</li>
                        <li>Tổng</li>
                    </ul>
                    <ul class="order_product">
                        @foreach (var item in Model)
                        {
                            decimal gia = (decimal)item.sp.Gia;
                            <li>@item.sp.Ten × @item.Soluong<span>@gia.ToString("##,#")</span></li>
                        }
                    </ul>
                    <ul class="total__amount">
                        @{ decimal tien = 0;}
                        @foreach (var item in Model)
                        {
                            decimal tongtien = item.Soluong * (decimal)item.sp.Gia;
                            tien = tien + tongtien;
                        }
                        <li>Tổng thanh toán <span>@tien.ToString("##,#")</span></li>
                    </ul>
                </div>
                <div id="accordion" class="checkout_accordion mt--30" role="tablist">
                    <div class="payment">
                        <div class="che__header" role="tab" id="headingOne">
                            <a class="checkout__title" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <span>Thanh toán qua ngân hàng</span>
                            </a>
                        </div>
                        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="payment-body">Chức năng này đang cập nhập</div>
                        </div>
                    </div>
                    <div class="payment">
                        <div class="che__header" role="tab" id="headingTwo">
                            <a class="collapsed checkout__title" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                <span>Thanh toán qua paymen</span>
                            </a>
                        </div>
                        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                            <div class="payment-body">Chức năng này đang cập nhập</div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

QuanLyBanSach/QuanLySach/QuanLySach/Views/GioHangs/CreateAcc.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="ht__bradcaump__area bg-image--4" style="background-image:url(../Assets/images/banner/banner4.jpg)">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Checkout</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="@Url.Action("Index","Home")">Trang chủ</a>
                        <span class="brd-separetor">/</span>
                        <span class="breadcrumb_item active">Checkout</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- Start Checkout Area -->
<section class="wn__checkout__area section-padding--lg bg__white">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-12">
                <form action="@Url.Action("CreateAcc","GioHangs")" method="post">
                    <div class="customer_details">
                        <h3>Thông tin khách hàng</h3>
                        <div class="customar__field">
                            <div class="input_box">
                                <label> Tên khách hàng <span>*</span></label>
                                <input type="hidden" value="" name="makh" required />
                                <input type="text" value="" name="tenkh" required>
                            </div>
                            <div class="input_box">
                                <label>Địa chỉ <span>*</span></label>
                                <input type="text" placeholder="Địa chỉ" value="" id="diachi" name="diachi" required>
                            </div>
                            <div class="margin_between">
                                <div class="input_box space_between">
                                    <label>Số điện thoại <span>*</span></label>
                                    <input type="text" value="" name="SoDienThoai" required>
                                </div>

                                <div class="input_box space_between">
                                    <label>Email  <span>*</span></label>
                                    <input type="email" value="" name="email" required>
                                </div>
                            </div>
                            <div class="input_box">
                                <label>Mật khẩu<span>*</span></label>
                                <input type="password" placeholder="Mật khẩu" value="" name="password" required>
                            </div>
                            <div class="input_box">
                                <label>Giao tới địa chỉ khác <span>*</span></label>
                                <input type="text" placeholder="Địa chỉ khác" value="" name="diachigiaohang" required>
                            </div>
                        </div>
                    </div>
                    <div class="create__account d-flex">
                        <input class="input-checkbox btn btn-primary" style="width:100%;" value="Đặt hàng" type="submit">
                    </div>
                </form>
            </div>
            <div class="col-lg-6 col-12 md-mt-40 sm-mt-40">
                <div class="wn__order__box">
                    <h3 class="onder__title">Đơn hàng của bạn</h3>
                    <ul class="order__total">
                        <li>Sản phẩm</li>
                        <li>Tổng</li>
                    </ul>
                    <ul class="order_product">
                        @foreach (var item in Model)
                        {
                            decimal gia = (decimal)item.sp.Gia;
                            <li>@item.sp.Ten × @item.Soluong<span>@gia.ToString("##,#")</span></li>
                        }
                    </ul>
                    <ul class="total__amount">
                        @{ decimal tien = 0;}
                        @foreach (var item in Model)
                        {
                            decimal tongtien = item.Soluong * (decimal)item.sp.Gia;
                            tien = tien + tongtien;
                        }
                        <li>Tổng thanh toán <span>@tien.ToString("##,#")</span></li>
                    </ul>
                </div>
                <div id="accordion" class="checkout_accordion mt--30" role="tablist">
                    <div class="payment">
                        <div class="che__header" role="tab" id="headingOne">
                            <a class="checkout__title" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <span>Thanh toán qua ngân hàng</span>
                            </a>
                        </div>
                        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="payment-body">Chức năng này đang cập nhập</div>
                        </div>
                    </div>
                    <div class="payment">
                        <div class="che__header" role="tab" id="headingTwo">
                            <a class="collapsed checkout__title" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                <span>Thanh toán qua paymen</span>
                            </a>
                        </div>
                        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                            <div class="payment-body">Chức năng này đang cập nhập</div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

QuanLyBanSach/QuanLySach/QuanLySach/Views/GioHangs/DatHangTC.cshtml
@model IEnumerable<QuanLySach.Models.ChiTietDonHang>
@using QuanLySach.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ht__bradcaump__area bg-image--4" style="background-image:url(../Assets/images/banner/banner4.jpg)">
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="bradcaump__inner text-center">
                <h2 class="bradcaump-title">Checkout</h2>
                <nav class="bradcaump-content">
                    <a class="breadcrumb_item" href="index.html">Home</a>
                    <span class="brd-separetor">/</span>
                    <span class="breadcrumb_item active">Checkout</span>
                </nav>
            </div>
        </div>
    </div>
</div>
</div>
<!-- End Bradcaump area -->
<!-- Start Checkout Area -->
<section class="wn__checkout__area section-padding--lg bg__white">
    <div class="container">
        <div class="row">
            @{ DonHang kh = (DonHang)Session["TTDonHang"]; }
            <div class="col-lg-12 col-12 md-mt-40 sm-mt-40">
                <div class="wn__order__box">
                    <h3 class="onder__title">Your order</h3>
                    <ul class="order__total">
                        <li>Product</li>
                        <li>Total</li>
                    </ul>
                    <ul class="order_product">
                        @foreach (var item in Model)
                        {
                            decimal gia = (decimal)item.SanPham.Gia;
                            <li>@item.SanPham.Ten × @item.SoLuong<span>@gia.ToString("##,#")</span></li>
                        }
                    </ul>
                    <ul class="order__total">
                        <li>Tên khách hàng</li>
                        <li>@kh.KhachHang.Ten</li>
                    </ul>
                    <ul class="order__total">
                        <li>Địa chỉ</li>
                        <li>@kh.KhachHang.DiaChi</li>
                    </ul>
                    <ul class="order__total">
                        <li>Số điện thoại</li>
                        <li>@kh.KhachHang.DienThoai</li>
                    </ul>

                    <ul class="order__total">
                        <li>Email</li>
                        <li>@kh.KhachHang.Email</li>
                    </ul>
                    <ul class="order__total">
                        <li>Ngày đặt hàng</li>
                        <li>@kh.NgayDatHang</li>
                    </ul>
                    @{
                        DateTime saveNow = DateTime.Now;
                        DateTime ngaygh = saveNow.AddDays(3);

                    }
                    <ul class="order__total">
                        <li>Ngày nhận hàng</li>
                        <li>@ngaygh</li>
                    </ul>
                    <ul class="total__amount">
                        @{ decimal tien = 0;}
                        @foreach (var item in Model)
                        {
                            decimal tongtien = (decimal)item.SoLuong * (decimal)item.SanPham.Gia;
                            tien = tien + tongtien;
                        }
                        <li>Tổng thanh toán <span>@tien.ToString("##,#")</span></li>
                    </ul>
                </div>
                <a href="@Url.Action("Index","Home")" style="width:100%;" class="btn btn-primary mt--100">Quay lại</a>
            </div>
        </div>
    </div>
</section>

QuanLyBanSach/QuanLySach/QuanLySach/Views/GioHangs/LoginAcc.cshtml
@model IEnumerable<QuanLySach.Models.GioHang>
@using QuanLySach.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="ht__bradcaump__area bg-image--4" style="background-image:url(../Assets/images/banner/banner4.jpg)">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bradcaump__inner text-center">
                    <h2 class="bradcaump-title">Checkout</h2>
                    <nav class="bradcaump-content">
                        <a class="breadcrumb_item" href="@Url.Action("Index","Home")">Trang chủ</a>
                        <span class="brd-separetor">/</span>
                        <span class="breadcrumb_item active">Checkout</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Bradcaump area -->
<!-- Start Checkout Area -->
<section class="wn__checkout__area section-padding--lg bg__white">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-12">
                <div class="customer_details">
                    <form action="@Url.Action("LoginAcc","GioHangs")" method="post">
                        <h3>Đăng nhập tài khoản</h3>
                        <div class="customar__field">
                            <div class="input_box">
                                <label> Số điện thoại<span>*</span></label>
                                <input type="text" placeholder="Nhập số điện thoại" name="SoDienThoai" required>
                            </div>
                            <div class="input_box">
                                <label>Mật khẩu<span>*</span></label>
                                <input type="password" placeholder="Nhập số mật khẩu" name="MatKhau" required>
                            </div>
                        </div>
                        @if (ViewBag.mess != null)
                        {<p class="text-danger">@ViewBag.mess</p>}
                        <div class="create__account d-flex">
                            <div class="wn__accountbox">
                                <input class="input-checkbox btn btn-primary" name="createaccount" value="Đăng nhập" type="submit">
                            </div>
                            <div class="wn__accountbox">
                                <a class="btn btn-dark ml-2" style="color:white" name="createaccount" href="@Url.Action("CreateAcc","GioHangs")">Tạo tài khoản</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-6 col-12 md-mt-40 sm-mt-40">
                <div class="wn__order__box">
                    <h3 class="onder__title">Đơn hàng của bạn</h3>
                    <ul class="order__total">
                        <li>Sản phẩm</li>
                        <li>Giá</li>
                    </ul>
                    <ul class="order_product">
                        @foreach (var item in Model)
                        {
                            decimal gia = (decimal)item.sp.Gia;
                            <li>@item.sp.Ten × @item.Soluong<span>@gia.ToString("##,#")</span></li>
                        }
                    </ul>
                    <ul class="total__amount">
                        @{ decimal tien = 0;}
                        @foreach (var item in Model)
                        {
                            decimal tongtien = item.Soluong * (decimal)item.sp.Gia;
                            tien = tien + tongtien;
                        }
                        <li>Tổng thanh toán <span>@tien.ToString("##,#")</span></li>
                    </ul>
                </div>
                <div id="accordion" class="checkout_accordion mt--30" role="tablist">
                    <div class="payment">
                        <div class="che__header" role="tab" id="headingOne">
                            <a class="checkout__title" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <span>Thanh toán qua thẻ ngân hàng</span>
                            </a>
                        </div>
                        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="payment-body">Tính năng này đang cập nhập</div>
                        </div>
                    </div>
                    <div class="payment">
                        <div class="che__header" role="tab" id="headingTwo">
                            <a class="collapsed checkout__title" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                <span>Thanh toán qua payment</span>
                            </a>
                        </div>
                        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                            <div class="payment-body">Tính năng này đang cập nhập</div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>